### ISSUE TITLE
Discord Link : Invite Invalid

### ISSUE THREAD

**Issue by Smankusors** [adafruit/Adafruit_CircuitPython_VL53L0X#20]
On the readme there's Discord chat badge. When clicked, Discord says "This invite may be expired, or you might not have permission to join."

**Comment by FoamyGuy** [comment]
Thank you @Smankusors for reporting this. It turned out to be a fairly widespread issue and we've gotten it fixed today.

fixed with: https://github.com/adafruit/Adafruit_CircuitPython_VL53L0X/commit/87b8438c71f3434bc967d6cdae2f6ca193005e95
