### ISSUE TITLE
Recreate I2CDevice when the device address changes

### ISSUE THREAD

**Issue by tannewt** [adafruit/Adafruit_CircuitPython_VL53L0X#25]
It fails with native bus device now because you can no longer change device address directly. So, instead of setting it, save the i2c bus and recreate it.

**Comment by caternuson** [comment]
I'll take this one. I'm looking for an excuse to get more familiar with the new native bus.

**Comment by tannewt** [comment]
Thank you!

**Comment by caternuson** [comment]
Hopefully fixed with #26
