### ISSUE TITLE
Multiple sensors using Qwiic connector

### ISSUE THREAD

**Issue by dovy** [adafruit/Adafruit_CircuitPython_VL53L0X#28]
I have two of these sensors I want to use at once. I assumed I could use them at the same time, but when I try to do the multi read:
```
xshut = [
    DigitalInOut(board.D7),
    DigitalInOut(board.D9),
    # add more VL53L0X sensors by defining their SHDN pins here
]
```

It just hangs there. I'm not sure exactly how to switch it to support running two at once. Any suggestions?

**Comment by ladyada** [comment]
hi you can post in the forums, but https://github.com/adafruit/Adafruit_CircuitPython_VL53L0X/blob/master/examples/vl53l0x_multiple_sensors.py is the only example we have.
