### ISSUE TITLE
Long Range

### ISSUE THREAD

**Issue by JBoisseau** [adafruit/Adafruit_CircuitPython_VL53L0X#29]
Dear all,
thanks for the toolset, very effective.

I don't find a python equivalent to 
https://forums.adafruit.com/viewtopic.php?f=19&p=713761
"
#if defined LONG_RANGE
  // lower the return signal rate limit (default is 0.25 MCPS)
  sensor.setSignalRateLimit(0.1);
  // increase laser pulse periods (defaults are 14 and 10 PCLKs)
  sensor.setVcselPulsePeriod(VL53L0X::VcselPeriodPreRange, 18);
  sensor.setVcselPulsePeriod(VL53L0X::VcselPeriodFinalRange, 14);
#endif
"
in order to use the Long Range mode.

I found the "signal_rate_limit" property, but  periodPreRange and FinalRange.

Can you help ?

Best

**Comment by jposada202020** [comment]
Hi there :) this kind of questions are better answer in he Adafruit discord channel. For what I saw in the code is there, but as I said, we hardly treat issues as a way to answer questions. Feel free to ask the question in the #help-with-circuitipython channel, I read the messages posted in there. Thanks
